### ISSUE TITLE
Falsche Übergabe von Settings

### ISSUE THREAD

**Issue by boitumeloruf** [boitumeloruf/3DMuVi#10]
Datei: CAlgoritmSettingsModel.cpp
Methode: saveSettings

Beschreibung: Übergabe der Adresse eines lokalen Objektes (data) an Algorithmus, führt zu segmentation fault. Lokales Objekt wird nach beenden der Funktion zerstört und steht nicht mehr für algorithmus zur vefügung.

**Comment by boitumeloruf** [comment]
Was passiert wenn keine Bearbeitung der Parameter vorgenommen wird und nur die Default Parameter verwendet werden sollen? Werden die Parameter dann ohne auf "Save" zu drücken übernommen?

**Comment by TimBrodb** [comment]
Mögliche Lösung für Issue #10 und Issue #11:
Es wurde ein Pointer auf ein Lokales Object zurückgegeben, das nach Ende der Methode nicht mehr existiert. Hier wird das QJason Object mit Hilfe des copyconstructor erzeugt und das plugin hällt somit immer einen pointer auf die letzten Parameter.

Hierfür müssten in allen Plugins die algorithm.h und die algorithm.cpp angepasst werden jedoch keine weiteren Datein.

in "algorithm.h"
QJsonObject *mSettings;
//zufügen von mQJson
QJsonObject mQJson;

in "algorithm.cpp"
void _CLASS_GEN(Algorithm)::setParameters(QJsonObject *settings){
//inhalt der Methode verändern
    mQJson = QJsonObject copy(*settings);
    mSettings = &mQJson;
}
