### ISSUE TITLE
Infoausgabe falls keine Bilder vorhanden

### ISSUE THREAD

**Issue by boitumeloruf** [boitumeloruf/3DMuVi#13]
Wenn ein Verzeichnis als Input gewählt wird, sollte eine Benachrichtigung kommen, wenn darin kein Bilder vorhanden sind. Alternativ kann man auch nach dem Laden der Bilder eine Ausgabe machen, wie viele Bilder denn geladen wurden.

**Comment by TimBrodb** [comment]
Wurde im Devbranch umgesetzt. Framwork Nachrichten können nun ins LogWidget geschrieben werden. Sobald Bilder geladen wurden wird Angezeigt wie viele Bilder geladen wurden.
