### ISSUE TITLE
Ausgabe zum Ergebnis der Parametervalidierung

### ISSUE THREAD

**Issue by boitumeloruf** [boitumeloruf/3DMuVi#14]
Erscheint eine entsprechende Ausgabe, wenn die eingestelltn Parameter nicht gültig sind? An dieser Stelle dürfte der Workflow nicht starten.

**Comment by TimBrodb** [comment]
Im Devbranch wurde eine Ensprechende Fehlermeldung zugefügt, sobald Parameter geändert wurde wird nun eine Fehlermeldung angezeigt wenn diese nicht Valide sind und somit garnicht erst an das Plugin übergeben werden. Allerdings werden diese in der Gui nicht zurückgesetzt. (Da bspw manche Werte nur im zusammenhang mit anderen geänderten Werten Valide sind, die Valide Methode aber bei jeder Änderung aufgerufen wird)
