### ISSUE TITLE
save und load in den Einstellungen der Algorithmen funktionieren nicht

### ISSUE THREAD

**Issue by wolfstefan** [boitumeloruf/3DMuVi#16]
Der Button save legt keine Datei für den jeweiligen Algorithmus in dem temporären Ordner an.
Die Funktion des Button load wurde auskommentiert.
Wäre es nicht sinnvoller, wenn man dem Benuzer einen Dateidialog anzeigt, um den Pfad zum Speichern bzw. Laden fest zu legen?

**Comment by TimBrodb** [comment]
Bug removed siehe Commit!
Achtung: Es dürfen auch ungültige ParameterDateien geladen werden. Die geladen Parameter werden nicht direkt verifiziert. Es kann aber jederzeit wieder eine neue Settingsdatei wie die default datei geladen werden.
