### ISSUE TITLE
Parameter werden nicht korrekt ausgegraut

### ISSUE THREAD

**Issue by TimBrodb** [boitumeloruf/3DMuVi#8]
Bei manchen Plugins werden nicht alle Parameter ausgegraut sobald das Programm gestartet wurde, sondern nur die ersten beiden Parameter (bspw FusionPlugin)

**Comment by wolfstefan** [comment]
Tritt das Problem immer noch auf? Ich kann es nicht bestätigen. Daher vermute ich, dass es vielleicht nur unter Windows auftritt.

**Comment by TimBrodb** [comment]
Auch unter Windows tritt das Problem nicht mehr auf.
